name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.x

      - name: Installer dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Notify Failures
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          message: |
            You shall not pass
            ${{github.actor}} created commit:
            Commit message: ${{github.event.commits[0].message}}

            Repository: ${{github.repository}}

            See Changes on: https://github.com/${{github.repository}}/commit/${{github.sha}}
